import { test } from '@japa/runner'
import type { FileSystem } from '@japa/file-system'
import { configure } from '../configure.js'
import { AppFactory } from '@adonisjs/core/factories/app'
import ConfigureCommand from '@adonisjs/core/commands/configure'

/**
 * config/auth.ts generated by `node ace add @adonisjs/auth` (session guard)
 */
const AUTH_CONFIG = `import { defineConfig } from '@adonisjs/auth'
import { sessionGuard, sessionUserProvider } from '@adonisjs/auth/session'
import type { InferAuthenticators, InferAuthEvents, Authenticators } from '@adonisjs/auth/types'

const authConfig = defineConfig({
  default: 'web',
  guards: {
    web: sessionGuard({
      useRememberMeTokens: false,
      provider: sessionUserProvider({
        model: () => import('#models/user')
      }),
    }),
  },
})

export default authConfig

declare module '@adonisjs/auth/types' {
  export interface Authenticators extends InferAuthenticators<typeof authConfig> {}
}
declare module '@adonisjs/core/types' {
  interface EventsList extends InferAuthEvents<Authenticators> {}
}
`

/**
 * app/models/user.ts generated by AdonisJS v7
 */
const USER_MODEL = `import { UserSchema } from '#database/schema'
import hash from '@adonisjs/core/services/hash'
import { compose } from '@adonisjs/core/helpers'
import { withAuthFinder } from '@adonisjs/auth/mixins/lucid'

export default class User extends compose(UserSchema, withAuthFinder(hash)) {}
`

type Action = { message: string; status: 'succeeded' | 'skipped' | 'failed'; reason?: string }

async function runConfigure(
  fs: FileSystem,
  options: {
    flags?: Record<string, any>
    confirm?: boolean
    authConfig?: string | null
    userModel?: string | null
  } = {}
) {
  await fs.create('tsconfig.json', JSON.stringify({ compilerOptions: { module: 'NodeNext' } }))
  if (options.authConfig !== null) {
    await fs.create('config/auth.ts', options.authConfig ?? AUTH_CONFIG)
  }
  if (options.userModel !== null) {
    await fs.create('app/models/user.ts', options.userModel ?? USER_MODEL)
  }

  const app = new AppFactory().create(fs.baseUrl, () => {})
  await app.init()

  const actions: Action[] = []
  const messages: string[] = []
  const logger = {
    action: (message: string) => ({
      succeeded: () => actions.push({ message, status: 'succeeded' }),
      skipped: (reason?: string) => actions.push({ message, status: 'skipped', reason }),
      failed: (reason?: string) => actions.push({ message, status: 'failed', reason }),
    }),
    info: (message: string) => messages.push(message),
    log: (message: string) => messages.push(message),
    error: (message: string) => messages.push(message),
    warning: (message: string) => messages.push(message),
    success: (message: string) => messages.push(message),
  }

  let prompted = false
  const command = new ConfigureCommand(
    app as any,
    {} as any,
    { flags: options.flags ?? {}, _: [], args: [], unknownFlags: [] } as any,
    { logger } as any,
    {
      confirm: async () => {
        prompted = true
        return options.confirm ?? true
      },
    } as any
  )

  await configure(command)

  const migrations = (await fs.exists('database/migrations'))
    ? ((await fs.readDir('database/migrations')) as any[]).map((file) => file.basename ?? file.name)
    : []

  return { command, actions, messages, prompted, migrations }
}

test.group('Configure hook', () => {
  test('add the jwt guard with refresh tokens', async ({ assert, fs }) => {
    const { actions, migrations, prompted } = await runConfigure(fs)

    assert.isTrue(prompted)

    const authConfig = await fs.contents('config/auth.ts')
    assert.include(authConfig, "import { jwtGuard } from '@maximemrf/adonisjs-jwt'")
    assert.include(authConfig, "import { tokensUserProvider } from '@adonisjs/auth/access_tokens'")
    assert.include(authConfig, 'jwt: jwtGuard({')
    assert.include(authConfig, "tokens: 'refreshTokens',")
    assert.include(authConfig, "refreshTokenExpiresIn: '7d',")
    // sessionUserProvider was already imported
    assert.lengthOf(authConfig.match(/sessionUserProvider \}/g) ?? [], 1)
    // the default guard is left untouched
    assert.include(authConfig, "default: 'web',")

    const userModel = await fs.contents('app/models/user.ts')
    assert.include(
      userModel,
      "import { DbAccessTokensProvider } from '@adonisjs/auth/access_tokens'"
    )
    assert.include(userModel, 'static refreshTokens = DbAccessTokensProvider.forModel(User, {')
    assert.include(userModel, "type: 'jwt_refresh_token',")

    assert.lengthOf(migrations, 1)
    assert.match(migrations[0], /^\d+_create_jwt_refresh_tokens_table\.ts$/)
    const migration = await fs.contents(`database/migrations/${migrations[0]}`)
    assert.include(migration, "protected tableName = 'jwt_refresh_tokens'")

    assert.deepEqual(
      actions.map((action) => action.status),
      ['succeeded', 'succeeded', 'succeeded']
    )
  })

  test('keep the style of the user files', async ({ assert, fs }) => {
    await runConfigure(fs)

    assert.equal(
      await fs.contents('config/auth.ts'),
      AUTH_CONFIG.replace(
        "from '@adonisjs/auth/types'\n",
        "from '@adonisjs/auth/types'\nimport { jwtGuard } from '@maximemrf/adonisjs-jwt'\nimport { tokensUserProvider } from '@adonisjs/auth/access_tokens'\n"
      ).replace(
        `      }),
    }),
  },`,
        `      }),
    }),
    jwt: jwtGuard({
      provider: sessionUserProvider({
        model: () => import('#models/user'),
      }),
      refreshTokenUserProvider: tokensUserProvider({
        tokens: 'refreshTokens',
        model: () => import('#models/user'),
      }),
      refreshTokenExpiresIn: '7d',
    }),
  },`
      )
    )

    assert.equal(
      await fs.contents('app/models/user.ts'),
      `import { UserSchema } from '#database/schema'
import hash from '@adonisjs/core/services/hash'
import { compose } from '@adonisjs/core/helpers'
import { withAuthFinder } from '@adonisjs/auth/mixins/lucid'
import { DbAccessTokensProvider } from '@adonisjs/auth/access_tokens'

export default class User extends compose(UserSchema, withAuthFinder(hash)) {
  static refreshTokens = DbAccessTokensProvider.forModel(User, {
    prefix: 'rt_',
    table: 'jwt_refresh_tokens',
    type: 'jwt_refresh_token',
    tokenSecretLength: 40,
  })
}
`
    )
  })

  test('use semicolons, empty guards and existing members like the user files', async ({
    assert,
    fs,
  }) => {
    await runConfigure(fs, {
      authConfig: `import { defineConfig } from '@adonisjs/auth';

const authConfig = defineConfig({
  default: 'jwt',
  guards: {},
});

export default authConfig;
`,
      userModel: `import { BaseModel, column } from '@adonisjs/lucid/orm';

export default class User extends BaseModel {
  @column({ isPrimary: true })
  declare id: number;
}
`,
    })

    assert.equal(
      await fs.contents('config/auth.ts'),
      `import { defineConfig } from '@adonisjs/auth';
import { jwtGuard } from '@maximemrf/adonisjs-jwt';
import { sessionUserProvider } from '@adonisjs/auth/session';
import { tokensUserProvider } from '@adonisjs/auth/access_tokens';

const authConfig = defineConfig({
  default: 'jwt',
  guards: {
    jwt: jwtGuard({
      provider: sessionUserProvider({
        model: () => import('#models/user'),
      }),
      refreshTokenUserProvider: tokensUserProvider({
        tokens: 'refreshTokens',
        model: () => import('#models/user'),
      }),
      refreshTokenExpiresIn: '7d',
    }),
  },
});

export default authConfig;
`
    )

    assert.equal(
      await fs.contents('app/models/user.ts'),
      `import { BaseModel, column } from '@adonisjs/lucid/orm';
import { DbAccessTokensProvider } from '@adonisjs/auth/access_tokens';

export default class User extends BaseModel {
  @column({ isPrimary: true })
  declare id: number;

  static refreshTokens = DbAccessTokensProvider.forModel(User, {
    prefix: 'rt_',
    table: 'jwt_refresh_tokens',
    type: 'jwt_refresh_token',
    tokenSecretLength: 40,
  });
}
`
    )
  })

  test('add the jwt guard without refresh tokens when declined', async ({ assert, fs }) => {
    const { migrations } = await runConfigure(fs, { confirm: false })

    const authConfig = await fs.contents('config/auth.ts')
    assert.include(authConfig, 'jwt: jwtGuard({')
    assert.notInclude(authConfig, 'refreshTokenUserProvider')
    assert.notInclude(authConfig, 'tokensUserProvider')

    assert.equal(await fs.contents('app/models/user.ts'), USER_MODEL)
    assert.lengthOf(migrations, 0)
  })

  test('use the {flag} flag without prompting')
    .with([
      { flag: '--refresh-tokens', value: true },
      { flag: '--no-refresh-tokens', value: false },
    ])
    .run(async ({ assert, fs }, row) => {
      const { prompted, migrations } = await runConfigure(fs, {
        flags: { 'refresh-tokens': row.value },
      })

      assert.isFalse(prompted)
      assert.lengthOf(migrations, row.value ? 1 : 0)
    })

  test('running the hook twice does not duplicate anything', async ({ assert, fs }) => {
    await runConfigure(fs)
    const authConfig = await fs.contents('config/auth.ts')
    const userModel = await fs.contents('app/models/user.ts')

    const { actions, migrations } = await runConfigure(fs, {
      authConfig: authConfig,
      userModel: userModel,
    })

    assert.equal(await fs.contents('config/auth.ts'), authConfig)
    assert.equal(await fs.contents('app/models/user.ts'), userModel)
    assert.lengthOf(migrations, 1)
    assert.deepEqual(
      actions.map((action) => action.status),
      ['skipped', 'skipped', 'skipped']
    )
  })

  test('fail when config/auth.ts does not exist', async ({ assert, fs }) => {
    const { command, messages, prompted } = await runConfigure(fs, { authConfig: null })

    assert.equal(command.exitCode, 1)
    assert.isFalse(prompted)
    assert.match(messages[0], /node ace add @adonisjs\/auth/)
  })

  test('print the code to add when the files cannot be updated', async ({ assert, fs }) => {
    // the migration is still created
    const { actions, migrations } = await runConfigure(fs, {
      authConfig: 'export default {}\n',
      userModel: null,
    })

    assert.equal(await fs.contents('config/auth.ts'), 'export default {}\n')
    assert.deepEqual(
      actions.map((action) => [action.status, action.message]),
      [
        ['skipped', 'update config/auth.ts'],
        ['skipped', 'update app/models/user.ts'],
        ['succeeded', `create database/migrations/${migrations[0]}`],
      ]
    )
    assert.include(actions[0].reason, 'jwt: jwtGuard({')
    assert.include(actions[1].reason, 'static refreshTokens = DbAccessTokensProvider.forModel(User')
  })
})
